### ISSUE TITLE
Misfunction

### ISSUE THREAD

**Issue by Addonman** [sylvanaar/wow-instant-messenger#42]
**Describe the bug**
Wim is creating whisper window next to general and combat window
**To Reproduce**
1.Recive or send whisper
2.Opens wim whisper window and blizz whisper window
3. Blizz whipser window needs to be closed and deleted after finishing conversation
**Expected behavior**
To open just wim whisper window and there isnt need to close blizz whisper window
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win10

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dartraiden** [comment]
Screenshot:
- player wispers me
- WIM window auto opens and contains message
- Blank chat tab also opens

![Wow_GzwIbrSSxm](https://user-images.githubusercontent.com/5046855/104110368-17caf780-52e8-11eb-8d4a-7b163ecc9306.jpg)

**Comment by MysticalOS** [comment]
Escape -- Interface -- Social -- New Whispers dropdown

set to inline. WIM intercepts whispers and squelches them from chat frame by design, but it can't stop the default UI from opening a new tab. that's done by default UI options, setting to inline makes it stop opening a new tab (which is blank by design becuse when WIM intercepts it doesn't show in chat window)
